// Code generated by tools/statsgen/main.go. DO NOT EDIT BY HAND.
//
// Regenerate from real repository history with:
//
//	go run tools/statsgen/main.go > pkg/api/stats_generated.go
//
// Every number below is counted from repositories on disk: production systems
// and commit totals come from `git rev-list --count HEAD` per tracked
// repository, and the engineering start year comes from the earliest commit
// date found. Edit tools/statsgen/main.go rather than this file.

package api

// GeneratedStats backs the statistics block on the public profile endpoint.
var GeneratedStats = []StatMetric{
	{Label: "Production systems", Value: "9", Sub: "Government, retail, travel"},
	{Label: "Commits on client work", Value: "653", Sub: "Across 9 repositories"},
	{Label: "Engineering since", Value: "2026", Sub: "Current practice"},
	{Label: "Clients served", Value: "8", Sub: "Blitar region and beyond"},
}
